"""FAISS vector store management."""

from __future__ import annotations

from typing import Optional, Sequence, Tuple

from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

from .config import AppConfig


class VectorStoreManager:
    """Create, load, persist, and clear the local FAISS vector index."""

    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self._embeddings: Optional[HuggingFaceEmbeddings] = None

    @property
    def embeddings(self) -> HuggingFaceEmbeddings:
        """Lazily load the embedding model on CPU."""
        if self._embeddings is None:
            self._embeddings = HuggingFaceEmbeddings(
                model_name=self.config.embedding_model_name,
                model_kwargs={"device": "cpu"},
                encode_kwargs={"normalize_embeddings": True},
            )
        return self._embeddings

    def build_from_documents(self, documents: Sequence[Document]) -> FAISS:
        """Build a new FAISS index and save it to disk."""
        vector_store = FAISS.from_documents(list(documents), self.embeddings)
        vector_store.save_local(str(self.config.vector_store_dir))
        return vector_store

    def load(self) -> Optional[FAISS]:
        """Load an existing FAISS index from disk if available."""
        index_path = self.config.vector_store_dir / "index.faiss"
        if not index_path.exists():
            return None

        return FAISS.load_local(
            str(self.config.vector_store_dir),
            self.embeddings,
            allow_dangerous_deserialization=True,
        )

    def clear(self) -> None:
        """Delete FAISS index artifacts generated by the app."""
        for path in self.config.vector_store_dir.iterdir():
            if path.is_file():
                path.unlink()

    def get_indexed_chunk_count(self) -> int:
        """Return how many chunks are stored in the current index."""
        vector_store = self.load()
        if vector_store is None:
            return 0
        return int(vector_store.index.ntotal)

    def similarity_search(self, query: str, top_k: int) -> Sequence[Tuple[Document, float]]:
        """Search the FAISS index and return chunk-score pairs."""
        vector_store = self.load()
        if vector_store is None:
            return []
        return vector_store.similarity_search_with_score(query, k=top_k)
